---
name: Antigravity-Server
version: "1.3.0"
slug: antigravity-server
description: '[老王杂谈说]：在您的浏览器中通过 NoVNC 流式传输 Antigravity AI IDE（带有 XFCE4 的 Linux 桌面）。'
url: https://gh-proxy.org/github.com/FaserF/hassio-addons/tree/master/antigravity-server
arch:
  - amd64
  - aarch64
image: ghcr.nju.edu.cn/faserf/hassio-addons-antigravity-server-{arch}
init: false
ingress: true
ingress_port: 6080
panel_icon: mdi:rocket-launch
panel_title: Antigravity
map:
  - share:rw
ports:
  6080/tcp: 6080
  5901/tcp: 5901
ports_description:
  6080/tcp: "NoVNC Web Interface (use Ingress for secure access)"
  5901/tcp: "VNC Client Port"
options:
  vnc_password: ""
  log_level: "info"
  autostart_antigravity: true
  install_android_tools: false
  install_dev_tools: false
  install_windows_tools: false
  install_linter_tools: false
  additional_packages: []
schema:
  vnc_password: match(^.{0,8}$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  autostart_antigravity: bool
  install_android_tools: bool?
  install_dev_tools: bool?
  install_windows_tools: bool?
  install_linter_tools: bool?
  additional_packages: list(str)?
