---
name: Komodo
version: 0.2.0
slug: komodo
image: ghcr.nju.edu.cn/faserf/hassio-addons-komodo-{arch}
description: '[老王杂谈说]：用于在多台服务器上构建和部署软件的工具'
url: https://gh-proxy.org/github.com/moghtech/komodo
arch:
  - amd64
init: false
ingress: true
ingress_port: 9120
panel_icon: mdi:lizard
options:
  log_level: "info"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
ports:
  9120/tcp: 9120
ports_description:
  9120/tcp: Web Interface
stage: experimental
