arch:
  - amd64
  - aarch64
boot: auto
description: "[老王杂谈说]：一个带有网络界面的卡坦岛游戏服务器。"
map:
  - type: addon_config
    read_only: false
    path: /tmp/data
init: false
version: "1"
name: tinc
options: {}
ports:
  4567/tcp: 4567
ports_description:
  4567/tcp: Web interface
schema: {}
slug: tinc
startup: services
upstream: v0.6.13
url: https://gh-proxy.org/github.com/jdeath/homeassistant-addons
ingress: false
