name: Freenom-dns-updater
version: 1.6.9
slug: freenom-dns-updater
description: 未翻译成功
  Freenom Registrar Domain Management - update dns records, Manage (add/update/remove)
  a domain's dns record, auto renew domains and more.
url: https://gh-proxy.com/github.com/FaserF/hassio-addons/tree/master/freenom-dns-updater
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
map:
  - share:rw
ingress: false
init: false
panel_icon: mdi:web-box
options:
  config_file:
  update_time_in_seconds: 86400
schema:
  config_file: str
  update_time_in_seconds: int
