name: Otter Wiki
version: "2.22.0"
upstream: 2.7.0
slug: otterwiki
description: >-
  [老王杂谈说]：Otter Wiki 是一个基于 Python 的用于协作内容管理的软件，被称为 Wiki。内容存储在 git 仓库中，用于跟踪所有更改。Markdown 被用作标记语言。Otter Wiki 使用微框架 Flask 用 Python 编写。halfmoon 用作 CSS 框架，CodeMirror 用作编辑器。Font Awesome Free 提供图标。
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.org/github.com/jdeath/homeassistant-addons"
ports:
  80/tcp: 8084
ports_description:
  80/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
    path: /app-data
image: redimp/otterwiki
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
ingress: false
ingress_port: 80
