build_from:
  aarch64: "ghcr.nju.edu.cn/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.nju.edu.cn/home-assistant/amd64-base:3.20"
  armhf: "ghcr.nju.edu.cn/home-assistant/armhf-base:3.20"
  armv7: "ghcr.nju.edu.cn/home-assistant/armv7-base:3.20"
  i386: "ghcr.nju.edu.cn/home-assistant/i386-base:3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: KNXD daemon"
  org.opencontainers.image.description: "Home Assistant Add-on: KNXD daemon"
  org.opencontainers.image.source: "https://gh-proxy.com/github.com/da-anda/hass-io-addons/tree/master/knxd"
args:
  KNXD_VERSION: 0.14.66
  KNXD_REPO: https://gh-proxy.com/github.com/knxd/knxd.git
