name: YT Music PO Token Generator
version: 0.8.5
slug: ytm_po_token_generator
description: 未翻译成功
url: https://gh-proxy.com/github.com/Brainicism/bgutil-ytdlp-pot-provider
image: brainicism/bgutil-ytdlp-pot-provider
arch:
  - amd64
  - aarch64
ports:
  "4416/tcp": 4416
