name: Radarr
version: 0.21.0
slug: radarr
description: 未翻译成功
url: https://gh-proxy.com/github.com/hassio-addons/addon-radarr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:7878]
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  7878/tcp: 7878
image: ghcr.nju.edu.cn/hassio-addons/radarr/{arch}
