name: Homepage
version: "1.13.2-0"
slug: homepage
description: "[老王杂谈说]：一个现代化的、完全静态、快速、安全且完全代理的、高度可定制的应用仪表板，集成了超过 100 种服务，并支持多种语言翻译。"
url: https://gh-proxy.org/github.com/bytenoodle/hassioaddon/tree/main/homepage
arch:
  - amd64
  - aarch64
map:
  - addon_config:rw
docker_api: true
environment:
  HOMEPAGE_ALLOWED_HOSTS: "*"
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Web interface port, default is 3000."
panel_icon: "mdi:broadcast"
webui: "http://[HOST]:[PORT:3000]"
