# Pin to release version tag at release time (e.g. :1.8.0)
build_from:
  amd64: ghcr.nju.edu.cn/kristianp26/ble-scale-sync:latest
  aarch64: ghcr.nju.edu.cn/kristianp26/ble-scale-sync:latest
  armv7: ghcr.nju.edu.cn/kristianp26/ble-scale-sync:latest
