---
build_from:
  aarch64: ghcr.nju.edu.cn/hassio-addons/base:17.2.1
  amd64: ghcr.nju.edu.cn/hassio-addons/base:17.2.1
  armv7: ghcr.nju.edu.cn/hassio-addons/base:17.2.1
#codenotary:
#  signer: lucio.tarantino@gmail.com
#  base_image: codenotary@frenck.dev
#cosign:
#  #base_identity: https://gh-proxy.com/github.com/home-assistant/builder/.*
#  identity: https://gh-proxy.com/github.com/dianlight/hassio-addons/.*
args:
  #  HDDTEMP_VERSION: "0.3-beta15"
  SRAT_VERSION: "v2024.12.0"
