name: Netboot.xyz
version: 1.8.6
slug: netboot-xyz
description: 未翻译成功
url: https://gh-proxy.com/github.com/FaserF/hassio-addons/tree/master/netboot-xyz
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
image: ghcr.nju.edu.cn/faserf/netboot-xyz-{arch}
host_network: true
#webui: http://[HOST]:[PORT:3000]
ingress: true
init: false
full_access: true
privileged:
  - NET_ADMIN
map:
  - media:rw
panel_icon: mdi:download-network
options:
  path: "/media/netboot/image"
  path_config: "/media/netboot/config"
  dhcp_range: 192.168.178.200
schema:
  path: str
  path_config: str
  dhcp_range: str
ports:
  "85": 85
  "3000": 3000
  69/udp: 69
ports_description:
  "85": NGINX server for hosting assets
  "3000": Web configuration interface for netboot-xyz - DO NOT CHANGE!
  69/udp: TFTP Port - DO NOT CHANGE!
