name: "linkding"
version: "1.40.0"
upstream: "1.40.0"
slug: linkding
description: 未翻译成功
  linkding is a bookmark manager that you can host yourself. It's designed be to be minimal, fast, and easy to set up using Docker
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.com/github.com/jdeath/homeassistant-addons"
ports:
  9090/tcp: 9090 
ports_description:
  9090/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
    path: /etc/linkding/data
image: sissbruecker/linkding
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:9090]"
ingress: false
ingress_port: 9090
