build_from:
  aarch64: "ghcr.nju.edu.cn/home-assistant/aarch64-base-python:3.9-alpine3.16"
  amd64: "ghcr.nju.edu.cn/home-assistant/amd64-base-python:3.9-alpine3.16"
  armhf: "ghcr.nju.edu.cn/home-assistant/armhf-base-python:3.9-alpine3.16"
  armv7: "ghcr.nju.edu.cn/home-assistant/armv7-base-python:3.9-alpine3.16"
  i386: "ghcr.nju.edu.cn/home-assistant/i386-base-python:3.9-alpine3.16"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: AC MQTT proxy"
  org.opencontainers.image.description: "AC MQTT proxy for home assistant."
  org.opencontainers.image.source: "https://gh-proxy.com/github.com/Arbuzov/hass-broadlink-ac-mqtt"
  org.opencontainers.image.licenses: "Apache License 2.0"