---
build_from:
  aarch64: ghcr.nju.edu.cn/home-assistant/aarch64-base:3.18
  amd64: ghcr.nju.edu.cn/home-assistant/amd64-base:3.18
  armhf: ghcr.nju.edu.cn/home-assistant/armhf-base:3.18
  armv7: ghcr.nju.edu.cn/home-assistant/armv7-base:3.18
  i386: ghcr.nju.edu.cn/home-assistant/i386-base:3.18
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  ZWAVEJS_SERVER_VERSION: 1.39.0
  ZWAVEJS_VERSION: 13.10.3
