name: ZeroTier One
version: 0.26.0
slug: zerotier
description: '[老王杂谈说]：使用一个随处一致的虚拟网络层，彻底简化您的网络。'
url: https://gh-proxy.org/github.com/hassio-addons/app-zerotier
startup: services
init: false
arch:
  - aarch64
  - amd64
ports:
  9993/tcp: 9993
ports_description:
  9993/tcp: ZeroTier's primary port
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
devices:
  - /dev/net/tun
map:
  - ssl:rw
options:
  networks: []
  api_auth_token: ''
schema:
  networks:
    - str
  api_auth_token: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.nju.edu.cn/hassio-addons/zerotier
