---
version: 2.1.0
slug: microwakeword
name: microwakeword
description: '[老王杂谈说]：使用怀俄明协议的microWakeWord'
url: https://gh-proxy.org/github.com/rhasspy/hassio-addons/tree/master/microwakeword
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
map:
  - share:rw
options:
  debug_logging: false
schema:
  debug_logging: bool
ports:
  "10400/tcp": null
homeassistant: 2023.9.0
