name: SQLite Web
version: 6.0.1
slug: sqlite-web
description: '[老王杂谈说]：探索你的 SQLite 数据库'
url: https://gh-proxy.org/github.com/hassio-addons/app-sqlite-web/tree/main/README.md
ingress: true
advanced: true
init: false
panel_icon: mdi:database
arch:
  - aarch64
  - amd64
map:
  - homeassistant_config:rw
  - share:rw
schema:
  database: str?
image: ghcr.nju.edu.cn/hassio-addons/sqlite-web
