name: "Stirling-PDF"
version: "0.46.2"
upstream: "0.46.2"
slug: stirling-pdf
description: 未翻译成功
  A robust, locally hosted web-based PDF manipulation tool
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.com/github.com/jdeath/homeassistant-addons"
ports:
  8080/tcp: 8080 
ports_description:
  8080/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
    path: /configs
environment:
  DOCKER_ENABLE_SECURITY: "false"
  INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "false"
image: ghcr.nju.edu.cn/stirling-tools/stirling-pdf
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
ingress: false
ingress_port: 8080 
