name: MyIP
version: "v7.2.0"
upstream: latest
slug: myip
description: >-
  [老王杂谈说]：最好的 IP 工具箱。轻松查看您的 IP、IP 地理位置、检测 DNS 泄露、检查 WebRTC 连接、速度测试、Ping 测试、MTR 测试、检查网站可用性、Whois 查询等！
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.org/github.com/jdeath/homeassistant-addons"
ports:
  18966/tcp: 18966
ports_description:
  18966/tcp: "Web Interface"
image: ghcr.nju.edu.cn/jason5ng32/myip
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:18966]"
ingress: false
ingress_port: 18966
