# 使用 EMQX MQTTX Web 镜像作为基础镜像
FROM docker.1ms.run/emqx/mqttx-web:latest

# 设置工作目录
WORKDIR /app

# 安装依赖并进行必要的配置
# 如果有特殊依赖或需要调整配置，添加相关命令

# 暴露 MQTTX Web 服务端口
EXPOSE 80

# 启动服务
#CMD ["http-server" "-p" "80"]
